name: bazel-farstack
base: core18
version: '3.1.0'
summary: Bazel - a fast, scalable, multi-language and extensible build system 
description: |
    {Fast, Correct} - Choose two

    Build and test software of any size, quickly and reliably.
      *  Speed up your builds and tests: Bazel rebuilds only what is necessary. With advanced local and distributed caching, optimized dependency analysis and parallel execution, you get fast and incremental builds.
      * One tool, multiple languages: Build and test Java, C++, Android, iOS, Go, and a wide variety of other language platforms. Bazel runs on Windows, macOS, and Linux.
      * Scalable: Bazel helps you scale your organization, codebase, and continuous integration solution. It handles codebases of any size, in multiple repositories or a huge monorepo.
      * Extensible to your needs: Easily add support for new languages and platforms with Bazel's familiar extension language. Share and re-use language rules written by the growing Bazel community.


grade: devel 
confinement: strict
architectures: [arm64, arm64]

apps:
  bazel:
    command: bazel
    plugs: [home]

parts:
  scripts:
    plugin: dump
    source: scripts

  bazel-bootstrap:
    after: [scripts]
    plugin: nil
    #source: https://github.com/bazelbuild/bazel
    #source-tag: '3.1.0'
    source: https://github.com/bazelbuild/bazel/releases/download/3.0.0/bazel-3.0.0-dist.zip
    build-packages:
      - build-essential
      - python
      - zip
      - unzip
      - openjdk-11-jdk
    override-build: |
      patch src/main/java/com/google/devtools/build/lib/syntax/BUILD < $SNAPCRAFT_STAGE/patches/BUILD_jni_md 
      patch scripts/bootstrap/compile.sh < $SNAPCRAFT_STAGE/patches/compile 

      env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp output/bazel $SNAPCRAFT_PART_INSTALL/bazel-bootstrap
    
  bazel:
    after: [bazel-bootstrap]
    plugin: nil
    source: https://github.com/bazelbuild/bazel.git
    source-tag: '3.1.0'
    build-packages:
      - build-essential
      - python
      - zip
      - unzip
      - openjdk-11-jdk
      - libc6-dev
      - gcc
      - libgcc-7-dev
      - python3-dev
      - dh-python
      - libc-dev-bin
      - libexpat1-dev
      - libpython3-dev
      - linux-libc-dev
    override-build: |
      patch src/main/java/com/google/devtools/build/lib/syntax/BUILD < $SNAPCRAFT_STAGE/patches/BUILD_jni_md 
 
      export PATH=$PATH:$SNAPCRAFT_STAGE/bin
      $SNAPCRAFT_STAGE/bazel-bootstrap build --local_ram_resources=2048  --jobs 3 --compilation_mode=opt --host_javabase=@local_jdk//:jdk //src:bazel  
      cp bazel-bin/src/bazel $SNAPCRAFT_PART_INSTALL
    prime:
      - -bazel-bootstrap

