name: bazel
base: core18
version: '3.0.0'
summary: Bazel - a fast, scalable, multi-language and extensible build system 
description: |
    {Fast, Correct} - Choose two

    Build and test software of any size, quickly and reliably.
      *  Speed up your builds and tests: Bazel rebuilds only what is necessary. With advanced local and distributed caching, optimized dependency analysis and parallel execution, you get fast and incremental builds.
      * One tool, multiple languages: Build and test Java, C++, Android, iOS, Go, and a wide variety of other language platforms. Bazel runs on Windows, macOS, and Linux.
      * Scalable: Bazel helps you scale your organization, codebase, and continuous integration solution. It handles codebases of any size, in multiple repositories or a huge monorepo.
      * Extensible to your needs: Easily add support for new languages and platforms with Bazel's familiar extension language. Share and re-use language rules written by the growing Bazel community.


grade: devel 
confinement: strict

apps:
  bazel:
    command: bin/get_envs $SNAP/bin/bazel
    plugs: [network-bind, network, home]

parts:
  bazel:
    after: [scripts]
    plugin: nil
    #source: https://github.com/bazelbuild/bazel
    #source-tag: '3.1.0'
    source: https://github.com/bazelbuild/bazel/releases/download/3.0.0/bazel-3.0.0-dist.zip
    build-packages:
      - build-essential
      - python
      - zip
      - unzip
      - openjdk-11-jdk
    stage-packages:
      - build-essential
      #- python
      #- zip
      #- unzip
      - openjdk-11-jdk
    override-build: |
      patch src/main/java/com/google/devtools/build/lib/syntax/BUILD < $SNAPCRAFT_STAGE/patches/BUILD_jni_md 
      patch scripts/bootstrap/compile.sh < $SNAPCRAFT_STAGE/patches/compile 

      env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp output/bazel $SNAPCRAFT_PART_INSTALL/bin
    
  scripts:
    plugin: dump
    source: scripts
